-- Supabase SQL — run this in the SQL Editor of dijjlppdljpcgyoakdnq.supabase.co
-- Creates tables needed by backend-clean (quiz + onboarding persistence).

-- Quiz / roadmap results
create table if not exists public.quiz_roadmaps (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email text,
  answers jsonb default '{}'::jsonb,
  persona_key text,
  result jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists quiz_roadmaps_email_idx on public.quiz_roadmaps (email);
create index if not exists quiz_roadmaps_user_id_idx on public.quiz_roadmaps (user_id);

alter table public.quiz_roadmaps enable row level security;

create policy "quiz_roadmaps_service_role_full"
  on public.quiz_roadmaps
  for all
  to service_role
  using (true)
  with check (true);

-- Onboarding state
create table if not exists public.onboarding_states (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  email text,
  superpower text,
  mode text default 'freeMode',
  current_step int default 1,
  steps jsonb default '[]'::jsonb,
  completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists onboarding_states_user_id_idx on public.onboarding_states (user_id);

alter table public.onboarding_states enable row level security;

create policy "onboarding_states_service_role_full"
  on public.onboarding_states
  for all
  to service_role
  using (true)
  with check (true);

-- User model preferences (used by set-model)
create table if not exists public.user_model_preferences (
  user_id text primary key,
  model_id text not null,
  updated_at timestamptz default now()
);

alter table public.user_model_preferences enable row level security;

create policy "user_model_preferences_service_role_full"
  on public.user_model_preferences
  for all
  to service_role
  using (true)
  with check (true);
